pub mod attributes;
pub mod cdata;
pub mod collections;
pub mod declarations;
pub mod doctype;
pub mod encoding;
pub mod inner;
pub mod instructions;
pub mod names;
pub mod namespaces;
pub mod objects;
pub mod self_closing;
pub mod values;
pub mod xmlns;
mod tag;